services:
  sundial-app:
    build: .
    restart: always
    volumes:
      - ${HOME}/.cache/huggingface:/home/nonroot/.cache/huggingface:rw
    ports:
      - 6060:6060
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - MAX_CONTENT_LENGTH=16777216
      - SQLALCHEMY_TRACK_MODIFICATIONS=0
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

    extra_hosts:
      - host.docker.internal:host-gateway